/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XmasiarikovaAmbulanceWlList {
    }
}
declare global {
    interface HTMLXmasiarikovaAmbulanceWlListElement extends Components.XmasiarikovaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXmasiarikovaAmbulanceWlListElement: {
        prototype: HTMLXmasiarikovaAmbulanceWlListElement;
        new (): HTMLXmasiarikovaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xmasiarikova-ambulance-wl-list": HTMLXmasiarikovaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XmasiarikovaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xmasiarikova-ambulance-wl-list": XmasiarikovaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xmasiarikova-ambulance-wl-list": LocalJSX.IntrinsicElements["xmasiarikova-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLXmasiarikovaAmbulanceWlListElement>;
        }
    }
}
